[package]
name = "fn-wol"
version = "0.1.0"
edition = "2021"
description = "飞牛 WOL 远程唤醒工具"
license = "MIT"

[dependencies]
tiny_http = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
if-addrs = "0.14"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
